// shared/engine-core/contracts.js

export const ENGINE_CORE_SCHEMA_VERSION = 1;

export const DTO_CAPS = Object.freeze({
  maxBlocks: 20,
  maxCandidates: 20,
  maxReasons: 20,
  maxProblems: 20,
  maxEvidence: 20,
  maxChecks: 20,
  maxLedgerReasons: 20,
  maxShadowEntries: 100,
  maxShadowReasons: 20,
  maxStringLength: 256,
  maxUserFacingKeyLength: 96,
  maxShadowIdLength: 96,
  maxNodesScanned: 5000,
  maxCandidatesSeen: 1000,
  maxVisualGraphNodes: 12,
  maxVisualGraphEdges: 48,
  maxVisualGraphGroups: 8,
  maxRepeatedRecordGroups: 8,
  maxRepeatedRecordSamples: 3,
  maxModeRegistryEntries: 4,
  maxActionRegistryEntries: 12,
  maxFeatureRegistryEntries: 32,
  maxShadowReplayBytes: 64 * 1024,
  maxShadowReplayEntryBytes: 1024,
});

export const PRIVACY_FORBIDDEN_KEYS = Object.freeze([
  'text',
  'rawText',
  'innerText',
  'textContent',
  'outerText',
  'html',
  'innerHTML',
  'outerHTML',
  'url',
  'href',
  'src',
  'fullUrl',
  'documentUrl',
  'pageUrl',
  'referrer',
  'location',
  'pathname',
  'query',
  'bodyText',
  'title',
  'selector',
  'selectors',
  'selectorPath',
  'cssSelector',
  'xpath',
  'domPath',
  'screenshot',
  'domSnapshot',
  'element',
  'rootElement',
  'node',
  'target',
  'handle',
  'rect',
  'domRect',
  'boundingClientRect',
  'clientRect',
]);

export const CONTRACT_IDS = Object.freeze({
  READING_COMFORT_TYPOGRAPHY: 'READING_COMFORT_TYPOGRAPHY',
  PAGE_CLARITY: 'PAGE_CLARITY',
  FOCUS_VISIBILITY: 'FOCUS_VISIBILITY',
  REDUCE_MOTION: 'REDUCE_MOTION',
  TARGET_SIZE: 'TARGET_SIZE',
});
