// shared/engine-core/enums.js

export const PAGE_TYPES = Object.freeze({
  ARTICLE: 'ARTICLE',
  DOC: 'DOC',
  FEED: 'FEED',
  VIDEO: 'VIDEO',
  FORM: 'FORM',
  DASHBOARD: 'DASHBOARD',
  SHOP: 'SHOP',
  SEARCH: 'SEARCH',
  WEB_APP: 'WEB_APP',
  UNKNOWN: 'UNKNOWN',
});

export const BLOCK_ROLES = Object.freeze({
  PRIMARY_CONTENT: 'PRIMARY_CONTENT',
  ARTICLE: 'ARTICLE',
  CARD: 'CARD',
  PLAYER: 'PLAYER',
  COMMENTS: 'COMMENTS',
  FORM: 'FORM',
  TABLE: 'TABLE',
  NAV: 'NAV',
  AD: 'AD',
  UNKNOWN: 'UNKNOWN',
});

export const ADAPTATION_ACTION_IDS = Object.freeze({
  READING_COMFORT_TYPOGRAPHY: 'READING_COMFORT_TYPOGRAPHY',
  PAGE_CLARITY: 'PAGE_CLARITY',
  DARK_COMFORT_THEME: 'DARK_COMFORT_THEME',
  FOCUS_VISIBILITY: 'FOCUS_VISIBILITY',
  REDUCE_MOTION: 'REDUCE_MOTION',
  TARGET_SIZE: 'TARGET_SIZE',
});

export const TARGET_KINDS = Object.freeze({
  READING_REGION: 'READING_REGION',
  RECORD_REGION: 'RECORD_REGION',
  FORM_REGION: 'FORM_REGION',
  DASHBOARD_REGION: 'DASHBOARD_REGION',
  MEDIA_REGION: 'MEDIA_REGION',
  APP_REGION: 'APP_REGION',
  FOCUSABLE_REGION: 'FOCUSABLE_REGION',
  BASELINE_OR_ABSTAIN: 'BASELINE_OR_ABSTAIN',
  NONE: 'NONE',
});

export const EFFECT_CLASSES = Object.freeze({
  SCOPED_READING_TYPOGRAPHY: 'SCOPED_READING_TYPOGRAPHY',
  REGION_LIGHT_CLARITY: 'REGION_LIGHT_CLARITY',
  FORM_LABEL_CLARITY: 'FORM_LABEL_CLARITY',
  RECORD_CARD_CLARITY: 'RECORD_CARD_CLARITY',
  DARK_THEME_ADAPTATION: 'DARK_THEME_ADAPTATION',
  FOCUS_VISIBLE_CLARITY: 'FOCUS_VISIBLE_CLARITY',
  TARGET_SIZE_ADJUSTMENT: 'TARGET_SIZE_ADJUSTMENT',
  DISTRACTION_REDUCTION: 'DISTRACTION_REDUCTION',
  NOOP: 'NOOP',
});

export const CAPABILITY_STATUSES = Object.freeze({
  SUPPORTED: 'SUPPORTED',
  CAPABILITY_MISSING: 'CAPABILITY_MISSING',
  INTENTIONAL_DENY: 'INTENTIONAL_DENY',
  HARD_BLOCKED: 'HARD_BLOCKED',
  SAFE_ABSTAIN: 'SAFE_ABSTAIN',
  UNSUPPORTED_PAGE_TYPE: 'UNSUPPORTED_PAGE_TYPE',
  UNSUPPORTED_TARGET: 'UNSUPPORTED_TARGET',
  UNSUPPORTED_EFFECT_CLASS: 'UNSUPPORTED_EFFECT_CLASS',
  MISSING_EXECUTOR: 'MISSING_EXECUTOR',
});

export const SUPPORT_LEVELS = Object.freeze({
  ACTIVE_RUNTIME: 'ACTIVE_RUNTIME',
  SHADOW_ONLY: 'SHADOW_ONLY',
  REPORT_ONLY: 'REPORT_ONLY',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});

export const ACTIVATION_STAGES = Object.freeze({
  REPORT_ONLY: 'REPORT_ONLY',
  SHADOW_ONLY: 'SHADOW_ONLY',
  MANUAL_LIMITED: 'MANUAL_LIMITED',
  MANUAL_MEDIUM_VERIFIED: 'MANUAL_MEDIUM_VERIFIED',
  VERIFIED: 'VERIFIED',
  ASSISTED: 'ASSISTED',
  AUTO: 'AUTO',
});

export const RUNTIME_EXECUTORS = Object.freeze({
  SCOPED_V2: 'SCOPED_V2',
  SAFE_DOWNGRADE_CSS: 'SAFE_DOWNGRADE_CSS',
  REGION_CLASS_TOKENS: 'REGION_CLASS_TOKENS',
  DARK_THEME_TRANSFORM: 'DARK_THEME_TRANSFORM',
  NOOP: 'NOOP',
  NONE: 'NONE',
});

export const OUTCOME_IDS = Object.freeze({
  READING_COMFORT: 'READING_COMFORT',
  FOCUS_NAVIGATION: 'FOCUS_NAVIGATION',
  MOTION_REDUCTION: 'MOTION_REDUCTION',
  TARGET_ACCESSIBILITY: 'TARGET_ACCESSIBILITY',
  COGNITIVE_DECLUTTERING: 'COGNITIVE_DECLUTTERING',
  FORM_CONFIDENCE: 'FORM_CONFIDENCE',
  MEDIA_CONTROL_SAFETY: 'MEDIA_CONTROL_SAFETY',
});

export const REASON_CODES = Object.freeze({
  ARTICLE_TEXT_DENSITY_HIGH: 'ARTICLE_TEXT_DENSITY_HIGH',
  DOC_STRUCTURE_DETECTED: 'DOC_STRUCTURE_DETECTED',
  VIDEO_MEDIA_DENSITY_HIGH: 'VIDEO_MEDIA_DENSITY_HIGH',
  FEED_CARD_REPETITION_DETECTED: 'FEED_CARD_REPETITION_DETECTED',
  FORM_CONTROLS_PRESENT: 'FORM_CONTROLS_PRESENT',
  DASHBOARD_TABLE_DENSITY_HIGH: 'DASHBOARD_TABLE_DENSITY_HIGH',
  SEARCH_RESULTS_STRUCTURE_DETECTED: 'SEARCH_RESULTS_STRUCTURE_DETECTED',
  SHOP_PRODUCT_GRID_DETECTED: 'SHOP_PRODUCT_GRID_DETECTED',
  UNKNOWN_LOW_CONFIDENCE: 'UNKNOWN_LOW_CONFIDENCE',
  TOP_CANDIDATES_AMBIGUOUS: 'TOP_CANDIDATES_AMBIGUOUS',
  VIDEO_PAGE_TYPOGRAPHY_BLOCKED: 'VIDEO_PAGE_TYPOGRAPHY_BLOCKED',
});

export const PROBLEM_CODES = Object.freeze({
  LOW_CONFIDENCE_PAGE_TYPE: 'LOW_CONFIDENCE_PAGE_TYPE',
  HIGH_INTERACTION_RISK: 'HIGH_INTERACTION_RISK',
  HIGH_LAYOUT_RISK: 'HIGH_LAYOUT_RISK',
  MODAL_OVERLAY_PRESENT: 'MODAL_OVERLAY_PRESENT',
});

export const ACTION_CONTEXT_SOURCES = Object.freeze({
  USER_REQUEST: 'USER_REQUEST',
  SUGGESTION: 'SUGGESTION',
  AUTO_APPLY: 'AUTO_APPLY',
  RESTORE: 'RESTORE',
  DEBUG: 'DEBUG',
});

export const ACTION_POLICY_DECISIONS = Object.freeze({
  ALLOW: 'ALLOW',
  DENY: 'DENY',
  SUGGEST_ONLY: 'SUGGEST_ONLY',
  REQUIRE_POST_APPLY_INSPECTION: 'REQUIRE_POST_APPLY_INSPECTION',
});

export const INVARIANT_CODES = Object.freeze({
  PAGE_TYPE_ALLOWED: 'PAGE_TYPE_ALLOWED',
  SAFE_SCOPE_REQUIRED: 'SAFE_SCOPE_REQUIRED',
  SCOPE_ROLE_ALLOWED: 'SCOPE_ROLE_ALLOWED',
  NO_BLOCKING_PROFILE_PROBLEMS: 'NO_BLOCKING_PROFILE_PROBLEMS',
  NO_MODAL_OVERLAY: 'NO_MODAL_OVERLAY',
  LOW_LAYOUT_RISK: 'LOW_LAYOUT_RISK',
  TOP_CANDIDATE_NOT_AMBIGUOUS: 'TOP_CANDIDATE_NOT_AMBIGUOUS',
  NO_HORIZONTAL_SCROLL_REGRESSION: 'NO_HORIZONTAL_SCROLL_REGRESSION',
  NO_CLIPPED_TEXT: 'NO_CLIPPED_TEXT',
  FOCUS_REMAINS_VISIBLE: 'FOCUS_REMAINS_VISIBLE',
  NO_CONTROL_OCCLUSION: 'NO_CONTROL_OCCLUSION',
  SCOPE_STILL_VISIBLE: 'SCOPE_STILL_VISIBLE',
});

export const INVARIANT_PHASES = Object.freeze({
  PRE_APPLY: 'PRE_APPLY',
  POST_APPLY: 'POST_APPLY',
  LEARNING_ELIGIBILITY: 'LEARNING_ELIGIBILITY',
});

export const INVARIANT_SEVERITIES = Object.freeze({
  INFO: 'INFO',
  WARN: 'WARN',
  BLOCK: 'BLOCK',
});

export const EVIDENCE_OPERATORS = Object.freeze({
  EQ: 'EQ',
  NEQ: 'NEQ',
  GT: 'GT',
  GTE: 'GTE',
  LT: 'LT',
  LTE: 'LTE',
  EXISTS: 'EXISTS',
});

export const POST_APPLY_CHECK_CODES = Object.freeze({
  HORIZONTAL_SCROLL: 'HORIZONTAL_SCROLL',
  HEIGHT_EXPANSION: 'HEIGHT_EXPANSION',
  CLIPPED_TEXT: 'CLIPPED_TEXT',
  DETACHED_SCOPE: 'DETACHED_SCOPE',
  HIDDEN_SCOPE: 'HIDDEN_SCOPE',
  FOCUS_LOST: 'FOCUS_LOST',
  CONTROL_OCCLUDED: 'CONTROL_OCCLUDED',
  CONTRAST_REGRESSION: 'CONTRAST_REGRESSION',
});

export const USER_OUTCOME_EVENTS = Object.freeze({
  ACCEPT: 'ACCEPT',
  UNDO: 'UNDO',
  ROLLBACK: 'ROLLBACK',
  IGNORE: 'IGNORE',
  NEVER_ON_SITE: 'NEVER_ON_SITE',
});

export const OUTCOME_LEDGER_EVENTS = Object.freeze({
  PROPOSED: 'PROPOSED',
  DENIED_BY_POLICY: 'DENIED_BY_POLICY',
  DENIED_BY_SHIELD: 'DENIED_BY_SHIELD',
  PENDING_APPLY: 'PENDING_APPLY',
  CSS_INSERTED: 'CSS_INSERTED',
  POST_APPLY_PASSED: 'POST_APPLY_PASSED',
  POST_APPLY_FAILED: 'POST_APPLY_FAILED',
  ROLLED_BACK: 'ROLLED_BACK',
  USER_ACCEPTED: 'USER_ACCEPTED',
  USER_UNDID: 'USER_UNDID',
  USER_NEVER_ON_SITE: 'USER_NEVER_ON_SITE',
  LEARNING_ELIGIBLE: 'LEARNING_ELIGIBLE',
  LEARNING_REJECTED: 'LEARNING_REJECTED',
});

export const SHADOW_NOT_APPLIED_REASONS = Object.freeze({
  SHADOW_MODE: 'SHADOW_MODE',
  POLICY_DISABLED: 'POLICY_DISABLED',
  USER_NOT_ASKED: 'USER_NOT_ASKED',
});

export const SHADOW_POLICY_IDS = Object.freeze({
  ACTION_POLICY_V1: 'ACTION_POLICY_V1',
});

export const ACTIVE_POLICY_DECISION_KINDS = Object.freeze({
  NOOP: 'NOOP',
  SUGGEST: 'SUGGEST',
  APPLY: 'APPLY',
});

export const SHADOW_COMPARISON_KINDS = Object.freeze({
  MATCH_NOOP: 'MATCH_NOOP',
  MATCH_POSITIVE: 'MATCH_POSITIVE',
  ACTIVE_MORE_AGGRESSIVE: 'ACTIVE_MORE_AGGRESSIVE',
  SHADOW_MORE_SENSITIVE: 'SHADOW_MORE_SENSITIVE',
  SHADOW_REJECTS_ACTIVE: 'SHADOW_REJECTS_ACTIVE',
  DIVERGENT_POSITIVE: 'DIVERGENT_POSITIVE',
});

export const FEATURE_IDS = Object.freeze({
  TEXT_SCALE: 'TEXT_SCALE',
  SPACING_PACK: 'SPACING_PACK',
  LINK_ENHANCEMENT: 'LINK_ENHANCEMENT',
  TEXT_RENDERING_REFINEMENT: 'TEXT_RENDERING_REFINEMENT',
  DARK_COMFORT_THEME: 'DARK_COMFORT_THEME',
  READING_RULER: 'READING_RULER',
  ULTRA_FOCUS: 'ULTRA_FOCUS',
  DISTRACTION_DIM: 'DISTRACTION_DIM',
  OVERLAY_BLUR: 'OVERLAY_BLUR',
  REDUCE_MOTION: 'REDUCE_MOTION',
  TARGET_BOOST: 'TARGET_BOOST',
  FOCUS_VISIBILITY: 'FOCUS_VISIBILITY',
  FOCUS_NOT_OBSCURED: 'FOCUS_NOT_OBSCURED',
  REFLOW_GUARD: 'REFLOW_GUARD',
  CONTRAST_GUARD: 'CONTRAST_GUARD',
  POST_APPLY_INSPECTION: 'POST_APPLY_INSPECTION',
  ROLLBACK: 'ROLLBACK',
});

export const FEATURE_MATURITIES = Object.freeze({
  STABLE: 'STABLE',
  ADVANCED: 'ADVANCED',
  EXPERIMENTAL: 'EXPERIMENTAL',
  SHADOW_ONLY: 'SHADOW_ONLY',
  SAFETY_ALWAYS_ON: 'SAFETY_ALWAYS_ON',
});

export const FEATURE_SECTIONS = Object.freeze({
  CORE: 'core',
  OPTIONAL: 'optional',
  ADVANCED: 'advanced',
  SAFETY: 'safety',
});

export const PAGE_TYPE_VALUES = Object.freeze(Object.values(PAGE_TYPES));
export const BLOCK_ROLE_VALUES = Object.freeze(Object.values(BLOCK_ROLES));
export const ADAPTATION_ACTION_ID_VALUES = Object.freeze(Object.values(ADAPTATION_ACTION_IDS));
export const TARGET_KIND_VALUES = Object.freeze(Object.values(TARGET_KINDS));
export const EFFECT_CLASS_VALUES = Object.freeze(Object.values(EFFECT_CLASSES));
export const CAPABILITY_STATUS_VALUES = Object.freeze(Object.values(CAPABILITY_STATUSES));
export const SUPPORT_LEVEL_VALUES = Object.freeze(Object.values(SUPPORT_LEVELS));
export const ACTIVATION_STAGE_VALUES = Object.freeze(Object.values(ACTIVATION_STAGES));
export const RUNTIME_EXECUTOR_VALUES = Object.freeze(Object.values(RUNTIME_EXECUTORS));
export const OUTCOME_ID_VALUES = Object.freeze(Object.values(OUTCOME_IDS));
export const REASON_CODE_VALUES = Object.freeze(Object.values(REASON_CODES));
export const PROBLEM_CODE_VALUES = Object.freeze(Object.values(PROBLEM_CODES));
export const ACTION_CONTEXT_SOURCE_VALUES = Object.freeze(Object.values(ACTION_CONTEXT_SOURCES));
export const ACTION_POLICY_DECISION_VALUES = Object.freeze(Object.values(ACTION_POLICY_DECISIONS));
export const INVARIANT_CODE_VALUES = Object.freeze(Object.values(INVARIANT_CODES));
export const INVARIANT_PHASE_VALUES = Object.freeze(Object.values(INVARIANT_PHASES));
export const INVARIANT_SEVERITY_VALUES = Object.freeze(Object.values(INVARIANT_SEVERITIES));
export const EVIDENCE_OPERATOR_VALUES = Object.freeze(Object.values(EVIDENCE_OPERATORS));
export const POST_APPLY_CHECK_CODE_VALUES = Object.freeze(Object.values(POST_APPLY_CHECK_CODES));
export const USER_OUTCOME_EVENT_VALUES = Object.freeze(Object.values(USER_OUTCOME_EVENTS));
export const OUTCOME_LEDGER_EVENT_VALUES = Object.freeze(Object.values(OUTCOME_LEDGER_EVENTS));
export const SHADOW_NOT_APPLIED_REASON_VALUES = Object.freeze(Object.values(SHADOW_NOT_APPLIED_REASONS));
export const SHADOW_POLICY_ID_VALUES = Object.freeze(Object.values(SHADOW_POLICY_IDS));
export const ACTIVE_POLICY_DECISION_KIND_VALUES = Object.freeze(Object.values(ACTIVE_POLICY_DECISION_KINDS));
export const SHADOW_COMPARISON_KIND_VALUES = Object.freeze(Object.values(SHADOW_COMPARISON_KINDS));
export const FEATURE_ID_VALUES = Object.freeze(Object.values(FEATURE_IDS));
export const FEATURE_MATURITY_VALUES = Object.freeze(Object.values(FEATURE_MATURITIES));
export const FEATURE_SECTION_VALUES = Object.freeze(Object.values(FEATURE_SECTIONS));

export function isEnumValue(values, value) {
  return values.includes(value);
}
